### ISSUE TITLE
error in the log

### ISSUE THREAD

**Issue by edkazic** [drc38/DiUS_Powersensor#298]
## Configuration

2023-11-29 10:09:47.398 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform dius
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 218, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 356, in unique_id
    return self._attr_unique_id
           ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dius/entity.py", line 22, in _attr_unique_id
    return data.get(Msg_keys.mac.value)
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-11-29 10:09:47.400 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up dius platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 218, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 356, in unique_id
    return self._attr_unique_id
           ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dius/entity.py", line 22, in _attr_unique_id
    return data.get(Msg_keys.mac.value)
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

## Debug log

```text

Add your logs here.

```

**Comment by drc38** [comment]
Try the latest release and see how you get on
