### ISSUE TITLE
Integration fails to start after upgrade to HA Core 2024.1.3

### ISSUE THREAD

**Issue by phyco1991** [drc38/DiUS_Powersensor#324]
## Version of the custom_component

v0.2.9

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

After upgrading from core-2024.1.2 to core-2024.1.3, the custom component for the integration fails to load. Attempting to uninstall and reinstall the integration yields no result. Reverting back to core-2024.1.2 resolves the issue.

## Debug log

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 11:42:24 AM (1 occurrences)
Last logged: 11:42:24 AM

Unexpected exception importing platform custom_components.dius.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dius/sensor.py", line 18, in <module>
    from .entity import DiusEntity
  File "/config/custom_components/dius/entity.py", line 10, in <module>
    class DiusEntity(CoordinatorEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_unique_id in subclass

```

**Comment by dasforsyth** [comment]
Getting the same issue here. I've enabled debugging, but thought it might be useful to see the startup homeasistant.log as well:

```
2024-01-18 05:56:10.430 INFO (MainThread) [custom_components.dius] 
-------------------------------------------------------------------
DiUS_Powersensor
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/drc38/DiUS_Powersensor/issues
-------------------------------------------------------------------

2024-01-18 05:56:10.507 INFO (MainThread) [custom_components.dius] The socket stream is connected, subscribing
2024-01-18 05:56:10.523 DEBUG (MainThread) [custom_components.dius] Received message json: {'type': 'instant_power', 'starttime': 1705510480, 'device': 'sensor', 'batteryMicrovolt': 3672032, 'mac': '***********', 'summation': 783601026, 'unit': 'w', 'duration': 30, 'power': 4264}
2024-01-18 05:56:11.299 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510528.113307, 'current': 0.06821129279813438, 'device': 'plug', 'mac': '***********', 'active_current': 0.00013682711794497568, 'reactive_current': 0.0003133142700769008, 'voltage': 233.63969870829487, 'summation': 21475510.193042655, 'unit': 'W', 'duration': 1.0398509999999999, 'power': 0.03504129964146515}
2024-01-18 05:56:13.059 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510529.153158, 'current': 0.07019826051090056, 'device': 'plug', 'mac': '***********', 'active_current': 0.00010708209230476355, 'reactive_current': 0.001181869018771094, 'voltage': 233.425700519139, 'summation': 21475510.226639617, 'unit': 'W', 'duration': 0.9591189999999999, 'power': 0.024886271445085872}
2024-01-18 05:56:13.059 DEBUG (MainThread) [custom_components.dius] Finished fetching dius data in 0.000 seconds (success: True)
2024-01-18 05:56:13.069 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.dius.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dius/sensor.py", line 18, in <module>
    from .entity import DiusEntity
  File "/config/custom_components/dius/entity.py", line 10, in <module>
    class DiusEntity(CoordinatorEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_unique_id in subclass
2024-01-18 05:56:13.072 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'dius.sensor': Platform not found (Exception importing custom_components.dius.sensor).
``` 

I found a bit interesting that after that error (about 30sec after) I started to get json logs for duis (flooded with them):
```
2024-01-18 05:56:13.661 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510530.112277, 'current': 0.071242310910872, 'device': 'plug', 'mac': '***********', 'active_current': 0.00038470233161340986, 'reactive_current': -0.0010688379213382882, 'voltage': 233.643650534381, 'summation': 21475510.25248183, 'unit': 'W', 'duration': 1.0385769999999999, 'power': 0.0873332424888618}
01-18 06:02:47.289 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510924.163446, 'current': 0.069093728558794, 'device': 'plug', 'mac': '***********', 'active_current': -0.00020623217777213722, 'reactive_current': -0.00018243615725996754, 'voltage': 236.2999413068107, 'summation': 21475498.71640356, 'unit': 'W', 'duration': 0.983753, 'power': -0.05587548652177876}
2024-01-18 06:02:48.247 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510925.147201, 'current': 0.06948041389211676, 'device': 'plug', 'mac': '***********', 'active_current': -0.0008725207521128884, 'reactive_current': 0.0006177050324617379, 'voltage': 236.20585121049015, 'summation': 21475498.662713934, 'unit': 'W', 'duration': 0.958171, 'power': -0.21059523283107168}
2024-01-18 06:02:49.289 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510926.105364, 'current': 0.07044018671944095, 'device': 'plug', 'mac': '***********', 'active_current': 0.00047195440682469867, 'reactive_current': 0.0001983001709347474, 'voltage': 236.29141905572214, 'summation': 21475498.44354698, 'unit': 'W', 'duration': 1.0417079999999999, 'power': 0.10690574404780706}
2024-01-18 06:02:50.249 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510927.147085, 'current': 0.07053338779978029, 'device': 'plug', 'mac': '***********', 'active_current': -0.0001516996307650817, 'reactive_current': 0.0009330023042479862, 'voltage': 236.29457611232695, 'summation': 21475498.54621104, 'unit': 'W', 'duration': 0.959745, 'power': -0.03780291141490866}
2024-01-18 06:02:51.289 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510928.106821, 'current': 0.06953494643912383, 'device': 'plug', 'mac': '***********', 'active_current': 0.0009528323213414611, 'reactive_current': -0.0004322943726377493, 'voltage': 236.33642563026933, 'summation': 21475498.506877434, 'unit': 'W', 'duration': 1.040664, 'power': 0.22841666207932168}
2024-01-18 06:02:52.252 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510929.147497, 'current': 0.07190661648350341, 'device': 'plug', 'mac': '***********', 'active_current': 1.4872512820106051e-05, 'reactive_current': -0.0012820106050931417, 'voltage': 236.35833183946275, 'summation': 21475498.726160526, 'unit': 'W', 'duration': 0.9609709999999999, 'power': 0.011563628881683498}
2024-01-18 06:02:52.753 DEBUG (MainThread) [custom_components.dius] Received message json: {'type': 'instant_power', 'starttime': 1705510900, 'device': 'sensor', 'batteryMicrovolt': 3672032, 'mac': '***********', 'summation': 783634355, 'unit': 'w', 'duration': 30, 'power': -560}
2024-01-18 06:02:53.290 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510930.108456, 'current': 0.06870506022376191, 'device': 'plug', 'mac': '***********', 'active_current': 0.0008745037538222359, 'reactive_current': 0.0004322943726377493, 'voltage': 236.55684103245417, 'summation': 21475498.738177802, 'unit': 'W', 'duration': 1.039315, 'power': 0.2021724161892068}
2024-01-18 06:02:54.250 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510931.147771, 'current': 0.07024287804936089, 'device': 'plug', 'mac': '***********', 'active_current': -0.0010896594392864364, 'reactive_current': -0.0008328607179259388, 'voltage': 236.55838752974472, 'summation': 21475498.93220138, 'unit': 'W', 'duration': 0.959598, 'power': -0.2603240981806138}
2024-01-18 06:02:55.288 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510932.10737, 'current': 0.06986412472287551, 'device': 'plug', 'mac': '***********', 'active_current': -0.0004828609162261098, 'reactive_current': -0.0008794612580956046, 'voltage': 236.60079458748703, 'summation': 21475498.661570378, 'unit': 'W', 'duration': 1.0391489999999999, 'power': -0.11039696928404029}
2024-01-18 06:02:56.247 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 12, 'type': 'instant_power', 'starttime': 1705510933.146522, 'current': 0.07217233871255596, 'device': 'plug', 'mac': '***********', 'active_current': 0.0006355520478458651, 'reactive_current': -0.0002845607452913624, 'voltage': 236.52025861402183, 'summation': 21475498.55563745, 'unit': 'W', 'duration': 0.958521, 'power': 0.14499752283369777}
2024-01-18 06:02:57.293 DEBUG (MainThread) [custom_components.dius] Received message json: {'source': 'BLE', 'count': 13, 'type': 'instant_power', 'starttime': 1705510934.10504, 'current': 0.0694605838750233, 'device': 'plug', 'mac': '***********', 'active_current': -0.000414447357253622, 'reactive_current': -0.0005939090119495684, 'voltage': 236.67645383939907, 'summation': 21475498.706346802, 'unit': 'W', 'duration': 1.042088, 'power': -0.10061915621128018}

``` 

But I'm still left with no devices/entities post the upgrade of HA.
