### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by KonsultInternetConsulting** [drc38/DiUS_Powersensor#326]
My integration has suddenly stopped. Using latest version and understand how it works, but I cannot see any entities in the integration. I have reinstalled and made sure my router hasn't changed IP... nope. 

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 5:29:34 PM (1 occurrences)
Last logged: 5:29:34 PM

Unexpected exception importing platform custom_components.dius.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dius/sensor.py", line 18, in <module>
    from .entity import DiusEntity
  File "/config/custom_components/dius/entity.py", line 10, in <module>
    class DiusEntity(CoordinatorEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_unique_id in subclass

**Comment by drc38** [comment]
See latest release

**Comment by KonsultInternetConsulting** [comment]
Cheers.
